MACRO PAUSE " Please, Select the Tool"
STRING $VarSelectedTool = INPUT ENTITY TOOL "Please select a tool from the list."
REAL  $VarToolDepth = INPUT  " Enter Z Stepdown (Must be Positive)" 
REAL  $VarCurvethickness = INPUT  " Enter Stock to leave per side " 

 STRING LIST $FeatureOptions = {"Feature Area Clearance" , "Pocket Area Clearance", "Finish Feature", "Finish Pocket"}

INT  $FeatureOptionSelected = INPUT CHOICE $FeatureOptions "Select Feature strategy:"

SWITCH $FeatureOptionSelected {


CASE 0

FORM STRATEGYSELECTOR
STRATEGYSELECTOR STRATEGY "Feature-Machining/Feature-Area-Clearance.ptf" NEW

IMPORT TEMPLATE ENTITY TOOLPATH TMPLTSELECTORGUI "Feature-Machining/Feature-Area-Clearance.ptf"

EDIT TPPAGE SWFeatures
EDIT TPFEATURES LISTUPDATE
 0 NEW
ACTIVATE FEATUREGROUP "1"
EDIT TPPAGE SWWorkplane
EDIT TPPAGE SWBlock
EDIT TPPAGE TOOL
ACTIVATE TOOL "Indexable Insert Diam: 25.0"
EDIT TPPAGE SWAreaClearance
EDIT PAR 'AreaClearance.Profile.CutDirection' 'any'
EDIT PAR 'CutDirection' 'any'
EDIT PAR 'Tolerance' ".1"
EDIT PAR 'Thickness' "1"
EDIT ZHEIGHTS AUTOMATIC STEPDOWN "1"
EDIT TPPAGE SWOffsetAreaClear
EDIT PAR 'AreaClearance.Offset.RemoveCusps' '0'
EDIT PAR 'AreaClearance.Offset.Order' 'inside_out'
EDIT TPPAGE SWFinishFlrWall
EDIT TPPAGE SWAreaFilterAClear
EDIT PAR 'AreaClearance.Slicer.Filter.Active' '1'
EDIT PAR 'AreaClearance.Slicer.Filter.Threshold' "1"
EDIT TPPAGE SWHighSpeedAClr
EDIT TPPAGE SWOrderBasic
EDIT TPPAGE SWApproach
EDIT TPPAGE SWAutoVerifMdlG
EDIT PAR 'CollisionCheck' '0'
EDIT PAR 'CollisionCheck' '1'
EDIT PAR 'ModelGougeCheck' '0'
EDIT PAR 'ModelGougeCheck' '1'
EDIT TPPAGE SWToolRapidMvClear
EDIT TPPAGE SWLeadsLinks
EDIT TPPAGE SWLeadIn
EDIT TOOLPATH LEADS LEADIN RAMP
FORM PMLLEADINRAMP EDIT TOOLPATH LEADS RAMPPAGE LEADINRAMPOPT1
EDIT TOOLPATH LEADS LEADIN RAMPOPT ZIGANGLE "1"
EDIT TOOLPATH LEADS LEADIN RAMPOPT HEIGHT_INCREMENT ".5"
EDIT TPPAGE SWLeadOut
EDIT TOOLPATH LEADS LEADOUT NONE
EDIT TOOLPATH LEADS LEADOUT2 NONE
EDIT TPPAGE SWLink
EDIT PAR 'Connections.Link[0].Type' 'on_surface'
EDIT PAR 'Connections.Link[0].ApplyConstraints' '0'
EDIT PAR 'Connections.DefaultLink[0].Type' 'safe'
EDIT TOOLPATH "1" CALCULATE
LEADINRAMP ACCEPT
FORM ACCEPT SFAreaClearance

MESSAGE INFO "Feature Area Clearance Calculed successfully"

BREAK


CASE 1


FORM STRATEGYSELECTOR
STRATEGYSELECTOR STRATEGY "Feature-Machining/Feature-Area-Clearance.ptf" NEW

IMPORT TEMPLATE ENTITY TOOLPATH TMPLTSELECTORGUI "Feature-Machining/Feature-Area-Clearance.ptf"

EDIT TPPAGE SWFeatures
EDIT TPFEATURES LISTUPDATE
 0 NEW
ACTIVATE FEATUREGROUP "1"
EDIT TPPAGE SWWorkplane
EDIT TPPAGE SWBlock
EDIT TPPAGE TOOL
ACTIVATE TOOL "Indexable Insert Diam: 25.0"
EDIT TPPAGE SWAreaClearance
EDIT PAR 'AreaClearance.Profile.CutDirection' 'any'
EDIT PAR 'CutDirection' 'any'
EDIT PAR 'Tolerance' ".1"
EDIT PAR 'Thickness' "1"
EDIT ZHEIGHTS AUTOMATIC STEPDOWN "1"
EDIT TPPAGE SWOffsetAreaClear
EDIT PAR 'AreaClearance.Offset.RemoveCusps' '0'
EDIT PAR 'AreaClearance.Offset.Order' 'inside_out'
EDIT TPPAGE SWFinishFlrWall
EDIT TPPAGE SWAreaFilterAClear
EDIT PAR 'AreaClearance.Slicer.Filter.Active' '1'
EDIT PAR 'AreaClearance.Slicer.Filter.Threshold' "1"
EDIT TPPAGE SWHighSpeedAClr
EDIT TPPAGE SWOrderBasic
EDIT TPPAGE SWApproach
EDIT TPPAGE SWAutoVerifMdlG
EDIT PAR 'CollisionCheck' '0'
EDIT PAR 'CollisionCheck' '1'
EDIT PAR 'ModelGougeCheck' '0'
EDIT PAR 'ModelGougeCheck' '1'
EDIT TPPAGE SWToolRapidMvClear
EDIT TPPAGE SWLeadsLinks
EDIT TPPAGE SWLeadIn
EDIT TOOLPATH LEADS LEADIN RAMP
FORM PMLLEADINRAMP EDIT TOOLPATH LEADS RAMPPAGE LEADINRAMPOPT1
EDIT TOOLPATH LEADS LEADIN RAMPOPT ZIGANGLE "1"
EDIT TOOLPATH LEADS LEADIN RAMPOPT HEIGHT_INCREMENT ".5"
EDIT TPPAGE SWLeadOut
EDIT TOOLPATH LEADS LEADOUT NONE
EDIT TOOLPATH LEADS LEADOUT2 NONE
EDIT TPPAGE SWLink
EDIT PAR 'Connections.Link[0].Type' 'on_surface'
EDIT PAR 'Connections.Link[0].ApplyConstraints' '0'
EDIT PAR 'Connections.DefaultLink[0].Type' 'safe'
EDIT TOOLPATH "1" CALCULATE
LEADINRAMP ACCEPT
FORM ACCEPT SFAreaClearance

BREAK


CASE 2

FORM STRATEGYSELECTOR
STRATEGYSELECTOR STRATEGY "Feature-Machining/Feature-Area-Clearance.ptf" NEW

IMPORT TEMPLATE ENTITY TOOLPATH TMPLTSELECTORGUI "Feature-Machining/Feature-Area-Clearance.ptf"

EDIT TPPAGE SWFeatures
EDIT TPFEATURES LISTUPDATE
 0 NEW
ACTIVATE FEATUREGROUP "1"
EDIT TPPAGE SWWorkplane
EDIT TPPAGE SWBlock
EDIT TPPAGE TOOL
ACTIVATE TOOL "Indexable Insert Diam: 25.0"
EDIT TPPAGE SWAreaClearance
EDIT PAR 'AreaClearance.Profile.CutDirection' 'any'
EDIT PAR 'CutDirection' 'any'
EDIT PAR 'Tolerance' ".1"
EDIT PAR 'Thickness' "1"
EDIT ZHEIGHTS AUTOMATIC STEPDOWN "1"
EDIT TPPAGE SWOffsetAreaClear
EDIT PAR 'AreaClearance.Offset.RemoveCusps' '0'
EDIT PAR 'AreaClearance.Offset.Order' 'inside_out'
EDIT TPPAGE SWFinishFlrWall
EDIT TPPAGE SWAreaFilterAClear
EDIT PAR 'AreaClearance.Slicer.Filter.Active' '1'
EDIT PAR 'AreaClearance.Slicer.Filter.Threshold' "1"
EDIT TPPAGE SWHighSpeedAClr
EDIT TPPAGE SWOrderBasic
EDIT TPPAGE SWApproach
EDIT TPPAGE SWAutoVerifMdlG
EDIT PAR 'CollisionCheck' '0'
EDIT PAR 'CollisionCheck' '1'
EDIT PAR 'ModelGougeCheck' '0'
EDIT PAR 'ModelGougeCheck' '1'
EDIT TPPAGE SWToolRapidMvClear
EDIT TPPAGE SWLeadsLinks
EDIT TPPAGE SWLeadIn
EDIT TOOLPATH LEADS LEADIN RAMP
FORM PMLLEADINRAMP EDIT TOOLPATH LEADS RAMPPAGE LEADINRAMPOPT1
EDIT TOOLPATH LEADS LEADIN RAMPOPT ZIGANGLE "1"
EDIT TOOLPATH LEADS LEADIN RAMPOPT HEIGHT_INCREMENT ".5"
EDIT TPPAGE SWLeadOut
EDIT TOOLPATH LEADS LEADOUT NONE
EDIT TOOLPATH LEADS LEADOUT2 NONE
EDIT TPPAGE SWLink
EDIT PAR 'Connections.Link[0].Type' 'on_surface'
EDIT PAR 'Connections.Link[0].ApplyConstraints' '0'
EDIT PAR 'Connections.DefaultLink[0].Type' 'safe'
EDIT TOOLPATH "1" CALCULATE
LEADINRAMP ACCEPT
FORM ACCEPT SFAreaClearance

BREAK


CASE 3

FORM STRATEGYSELECTOR
STRATEGYSELECTOR STRATEGY "Feature-Machining/Feature-Area-Clearance.ptf" NEW

IMPORT TEMPLATE ENTITY TOOLPATH TMPLTSELECTORGUI "Feature-Machining/Feature-Area-Clearance.ptf"

EDIT TPPAGE SWFeatures
EDIT TPFEATURES LISTUPDATE
 0 NEW
ACTIVATE FEATUREGROUP "1"
EDIT TPPAGE SWWorkplane
EDIT TPPAGE SWBlock
EDIT TPPAGE TOOL
ACTIVATE TOOL "Indexable Insert Diam: 25.0"
EDIT TPPAGE SWAreaClearance
EDIT PAR 'AreaClearance.Profile.CutDirection' 'any'
EDIT PAR 'CutDirection' 'any'
EDIT PAR 'Tolerance' ".1"
EDIT PAR 'Thickness' "1"
EDIT ZHEIGHTS AUTOMATIC STEPDOWN "1"
EDIT TPPAGE SWOffsetAreaClear
EDIT PAR 'AreaClearance.Offset.RemoveCusps' '0'
EDIT PAR 'AreaClearance.Offset.Order' 'inside_out'
EDIT TPPAGE SWFinishFlrWall
EDIT TPPAGE SWAreaFilterAClear
EDIT PAR 'AreaClearance.Slicer.Filter.Active' '1'
EDIT PAR 'AreaClearance.Slicer.Filter.Threshold' "1"
EDIT TPPAGE SWHighSpeedAClr
EDIT TPPAGE SWOrderBasic
EDIT TPPAGE SWApproach
EDIT TPPAGE SWAutoVerifMdlG
EDIT PAR 'CollisionCheck' '0'
EDIT PAR 'CollisionCheck' '1'
EDIT PAR 'ModelGougeCheck' '0'
EDIT PAR 'ModelGougeCheck' '1'
EDIT TPPAGE SWToolRapidMvClear
EDIT TPPAGE SWLeadsLinks
EDIT TPPAGE SWLeadIn
EDIT TOOLPATH LEADS LEADIN RAMP
FORM PMLLEADINRAMP EDIT TOOLPATH LEADS RAMPPAGE LEADINRAMPOPT1
EDIT TOOLPATH LEADS LEADIN RAMPOPT ZIGANGLE "1"
EDIT TOOLPATH LEADS LEADIN RAMPOPT HEIGHT_INCREMENT ".5"
EDIT TPPAGE SWLeadOut
EDIT TOOLPATH LEADS LEADOUT NONE
EDIT TOOLPATH LEADS LEADOUT2 NONE
EDIT TPPAGE SWLink
EDIT PAR 'Connections.Link[0].Type' 'on_surface'
EDIT PAR 'Connections.Link[0].ApplyConstraints' '0'
EDIT PAR 'Connections.DefaultLink[0].Type' 'safe'
EDIT TOOLPATH "1" CALCULATE
LEADINRAMP ACCEPT
FORM ACCEPT SFAreaClearance

BREAK

}





